const GUESTS = [
  { name: "Mattia Doronzo", table: "Sposi" },
  { name: "Micol Levi", table: "Sposi" },
  { name: "Michele Doronzo", table: "Giardino Yuyuan" },
  { name: "Anna Rociola", table: "Giardino Yuyuan" },
  { name: "Gianfranco Falcone", table: "Giardino Yuyuan" },
  { name: "Alessia Doronzo", table: "Giardino Yuyuan" },
  { name: "Federico Pio Falcone", table: "Giardino Yuyuan" },
  { name: "Ruggero Doronzo", table: "Giardino Yuyuan" },
  { name: "Silvana Dimatteo", table: "Giardino Yuyuan" },
  { name: "Marianna Doronzo", table: "Emerald Beach" },
  { name: "Giovanni Schittulli", table: "Emerald Beach" },
  { name: "Giuseppe Doronzo", table: "Emerald Beach" },
  { name: "Anna Daleno", table: "Emerald Beach" },
  { name: "Donatella Doronzo", table: "Emerald Beach" },
  { name: "Marco Tesio", table: "Emerald Beach" },
  { name: "Morena Gho", table: "Emerald Beach" },
  { name: "Domenica Gho", table: "Emerald Beach" },
  { name: "Emanuele Tesio", table: "Lago Baofeng" },
  { name: "Lorenzo Tesio", table: "Lago Baofeng" },
  { name: "Silvia Torretta", table: "Lago Baofeng" },
  { name: "Baldassarre Doronzo", table: "Grande Muraglia" },
  { name: "Antonella Tesio", table: "Grande Muraglia" },
  { name: "Nicolò Doronzo", table: "Xi'an" },
  { name: "Angela Borlacchi", table: "Xi'an" },
  { name: "Salvatore Doronzo", table: "Emerald Beach" },
  { name: "Maria Stano", table: "Emerald Beach" },
  { name: "Gianluca Doronzo", table: "Giardino Yuyuan" },
  { name: "Edoardo Doronzo", table: "Giardino Yuyuan" },
  { name: "Lorenzo Doronzo", table: "Giardino Yuyuan" },
  { name: "Carlo Giuliano", table: "Porta del Paradiso" },
  { name: "Zuzanna Juzwik", table: "Porta del Paradiso" },
  { name: "Federico Vitiello", table: "Porta del Paradiso" },
  { name: "Anna Giachetti", table: "Porta del Paradiso" },
  { name: "Giovenale Moirano", table: "Porta del Paradiso" },
  { name: "Gloria Sdanganelli", table: "Porta del Paradiso" },
  { name: "Carlo Mariani", table: "Porta del Paradiso" },
  { name: "Francesco Bruno", table: "Porta del Paradiso" },
  { name: "Alice Dallan", table: "Porta del Paradiso" },
  { name: "Matteo Airaldi", table: "Okinawa" },
  { name: "Iolanda Petrone", table: "Okinawa" },
  { name: "Andrea Mina", table: "Okinawa" },
  { name: "Yunwei Liu", table: "Okinawa" },
  { name: "Giacomo Olivero", table: "Porta del Paradiso" },
  { name: "Martina Sorba", table: "Porta del Paradiso" },
  { name: "Alessio Gastino", table: "Palazzo d'estate" },
  { name: "Carola Aschieri", table: "Palazzo d'estate" },
  { name: "Raimondo Pili", table: "Okinawa" },
  { name: "Andrea Aguggia", table: "Okinawa" },
  { name: "Francesco Giuliano", table: "Xi'an" },
  { name: "Giorgia Vitiello", table: "Naha" },
  { name: "Giovanni Regaiolo", table: "Naha" },
  { name: "Antonia Moirano", table: "Naha" },
  { name: "Giacomo Galanti", table: "Naha" },
  { name: "Amedeo Ramieri", table: "Okinawa" },
  { name: "Giulia Boschi", table: "Okinawa" },
  { name: "Lorenzo Aimar", table: "Okinawa" },
  { name: "Anna Carla Zardo", table: "Okinawa" },
  { name: "Lorenzo Bedogni", table: "Tempio del Cielo" },
  { name: "Roberta De Paolis", table: "Tempio del Cielo" },
  { name: "Nicola Bottasso", table: "Tempio del Cielo" },
  { name: "Cristina Crosetto", table: "Tempio del Cielo" },
  { name: "Paola Faccenda", table: "Naha" },
  { name: "Sofia Faccenda", table: "Naha" },
  { name: "Paola Gonella", table: "Naha" },
  { name: "Daniel Trecco", table: "Naha" },
  { name: "Monica Bonardi", table: "Tempio del Cielo" },
  { name: "Edoardo Castagneris", table: "Tempio del Cielo" },
  { name: "Davide Fassina", table: "Tempio del Cielo" },
  { name: "Emma Gallone", table: "Tempio del Cielo" },
  { name: "Stefano Bianco", table: "Tempio del Cielo" },
  { name: "Agnese Ciliberti", table: "Tempio del Cielo" },
  { name: "Antonio Lanfranchi", table: "Giappone" },
  { name: "Flavia Di Cosmo", table: "Giappone" },
  { name: "Andrea Visalli", table: "Piazza Tienanmen" },
  { name: "Daniela Vinci", table: "Piazza Tienanmen" },
  { name: "Amedeo Burato", table: "Xi'an" },
  { name: "Elena Bonino", table: "Xi'an" },
  { name: "Stefano Trucco", table: "Xi'an" },
  { name: "Ilaria Ferro", table: "Xi'an" },
  { name: "Giorgio Marengo", table: "Giappone" },
  { name: "Silvia Fantino", table: "Giappone" },
  { name: "Andrea Rinaudo", table: "Giappone" },
  { name: "Cristina Roberto", table: "Giappone" },
  { name: "Michele De Benedictis", table: "Giappone" },
  { name: "Giuseppina Mistretta", table: "Giappone" },
  { name: "Umberto Barbero", table: "Giappone" },
  { name: "Serena Bianciotto", table: "Giappone" },
  { name: "Marta Grinza", table: "Piazza Tienanmen" },
  { name: "Michele Salvagno", table: "Piazza Tienanmen" },
  { name: "Chiara Patelli", table: "Piazza Tienanmen" },
  { name: "Francesca De Lio", table: "Piazza Tienanmen" },
  { name: "Francesco Fioravanti", table: "Piazza Tienanmen" },
  { name: "Gabriella De Lio", table: "Piazza Tienanmen" },
  { name: "Giulia De Lio", table: "Piazza Tienanmen" },
  { name: "Matteo Bellettini", table: "Piazza Tienanmen" },
  { name: "Pier Luigi Mucciolo", table: "Xi'an" },
  { name: "Roberto Giuliano", table: "Castello si Shuri" },
  { name: "Rosalia Rizzo", table: "Castello si Shuri" },
  { name: "Raffaele Vitiello", table: "Castello si Shuri" },
  { name: "Anna Frascà", table: "Castello si Shuri" },
  { name: "Fulvio Moirano", table: "Castello si Shuri" },
  { name: "Maria Teresa Giachino Amistà", table: "Castello si Shuri" },
  { name: "Corrado Bedogni", table: "Castello si Shuri" },
  { name: "Laila Melli", table: "Castello si Shuri" },
  { name: "Silvia Olivero", table: "Grande Muraglia" },
  { name: "Claudio Grossi", table: "Grande Muraglia" },
  { name: "Cristina Tosatto", table: "Grande Muraglia" },
  { name: "Guido Ariotti Canepa", table: "Castello si Shuri" },
  { name: "Elena Ghione", table: "Castello si Shuri" },
  { name: "Ezio Zerbino", table: "Grande Muraglia" },
  { name: "Antonietta Lombardo", table: "Grande Muraglia" },
  { name: "Giuliano Previati", table: "Grande Muraglia" },
  { name: "Elisabetta Grosso", table: "Grande Muraglia" },
  { name: "Gianfranco Ferrero", table: "Grande Muraglia" },
  { name: "Emanuele Trono", table: "Xi'an" },
  { name: "Susanna Boitano", table: "Xi'an" },
  { name: "Camilla Bava", table: "Okinawa" },
  { name: "Giampaolo Levi", table: "Isole Kerama" },
  { name: "Maria Grazia Vaccaro", table: "Isole Kerama" },
  { name: "Gavriel Levi", table: "Shanghai" },
  { name: "Ottavia Garibaldi", table: "Shanghai" },
  { name: "Sergio Levi", table: "Città Proibita" },
  { name: "Cristina Bellone", table: "Città Proibita" },
  { name: "Davide Levi", table: "Lago Baofeng" },
  { name: "Marta Levi", table: "Lago Baofeng" },
  { name: "Caterina Molinari", table: "Lago Baofeng" },
  { name: "Barbara Levi", table: "Città Proibita" },
  { name: "Fabrizio Barbieri", table: "Città Proibita" },
  { name: "Bianca Barbieri", table: "Lago Baofeng" },
  { name: "Alice Barbieri", table: "Lago Baofeng" },
  { name: "Marcello Ollearis", table: "Lago Baofeng" },
  { name: "Cesare Gandiglio", table: "Città Proibita" },
  { name: "Ornella Gandiglio", table: "Città Proibita" },
  { name: "Federico Gandiglio", table: "Cina" },
  { name: "Erika Gandiglio", table: "Cina" },
  { name: "Virginia Gandiglio", table: "Cina" },
  { name: "Vittoria Gandiglio", table: "Cina" },
  { name: "Ileana Levi", table: "Città Proibita" },
  { name: "Dario Rocci", table: "Città Proibita" },
  { name: "Gabriele Rocci", table: "Lago Baofeng" },
  { name: "Donatella Bellone", table: "Città Proibita" },
  { name: "Ludovica Blandino", table: "Cina" },
  { name: "Edoardo Blandino", table: "Cina" },
  { name: "Giulia Blandino", table: "Cina" },
  { name: "Ugo Attisani", table: "Naha" },
  { name: "Andrea Giordano", table: "Naha" },
  { name: "Riccardo Blandino", table: "Cina" },
  { name: "Eleonora Blandino", table: "Cina" },
  { name: "Paola Stura", table: "Pechino" },
  { name: "Matthew Diliberto", table: "Pechino" },
  { name: "Shlomi Sofer", table: "Esercito di Terracotta" },
  { name: "Stefania Ivaldi", table: "Esercito di Terracotta" },
  { name: "Micol Piperno", table: "Shanghai" },
  { name: "Gaetano Briguglio", table: "Shanghai" },
  { name: "Carlo Briguglio Piperno", table: "Shanghai" },
  { name: "Rubén Piperno", table: "Shanghai" },
  { name: "Tina Piperno", table: "Esercito di Terracotta" },
  { name: "Anna Mangano", table: "Zamami" },
  { name: "Elena Ovazza", table: "Shanghai" },
  { name: "Ilaria Bello", table: "Zamami" },
  { name: "Giulia Rosso", table: "Zamami" },
  { name: "Edoardo Favale", table: "Zamami" },
  { name: "Clotilde Trevisson", table: "Zamami" },
  { name: "Leonora Mascia", table: "Palazzo d'estate" },
  { name: "Ivan Filidoro", table: "Palazzo d'estate" },
  { name: "Paolo Cucchi", table: "Palazzo d'estate" },
  { name: "Sara Gamba", table: "Palazzo d'estate" },
  { name: "Antonio Solano", table: "Oriental Pearl Tower" },
  { name: "Fulvia Colzani", table: "Oriental Pearl Tower" },
  { name: "Andrea Solano", table: "Oriental Pearl Tower" },
  { name: "Carmelo Zinnato", table: "Oriental Pearl Tower" },
  { name: "Virginia Emanuele", table: "Oriental Pearl Tower" },
  { name: "Federica Vicino", table: "Palazzo d'estate" },
  { name: "Alessandra Meloni", table: "Oriental Pearl Tower" },
  { name: "Francesca Montanari", table: "Oriental Pearl Tower" },
  { name: "Chiara Gillio", table: "Oriental Pearl Tower" },
  { name: "Nicolò Savio", table: "Oriental Pearl Tower" },
  { name: "Alessandro Ruggiero", table: "Tempio del Buddha di giada" },
  { name: "Sara Audisio", table: "Tempio del Buddha di giada" },
  { name: "Emanuele Montalto", table: "Tempio del Buddha di giada" },
  { name: "Chiara Ienopoli", table: "Tempio del Buddha di giada" },
  { name: "Greta Guazzotti", table: "Tempio del Buddha di giada" },
  { name: "Michele Cucco", table: "Tempio del Buddha di giada" },
  { name: "Andrea Masino", table: "Tempio del Buddha di giada" },
  { name: "Federica Seardo", table: "Tempio del Buddha di giada" },
  { name: "Alessandro Provini", table: "Tempio del Buddha di giada" },
  { name: "Maria Giulia Gardin", table: "Tempio del Buddha di giada" },
  { name: "Leonardo Rabajoli", table: "Zhangjiajie" },
  { name: "Caterina Brossa", table: "Zhangjiajie" },
  { name: "Federico Maggio", table: "Zhangjiajie" },
  { name: "Elena Grifoni", table: "Zhangjiajie" },
  { name: "Matteo Rotondo", table: "Zamami" },
  { name: "Elisa Sinigaglia", table: "Zamami" },
  { name: "Eugenio Garibaldi", table: "Shanghai" },
  { name: "Edoardo Sapey", table: "Zamami" },
  { name: "Giulia Ferrero", table: "Zamami" },
  { name: "Andrea Casiraghi", table: "Shanghai" },
  { name: "Allegra Ovazza", table: "Shanghai" },
  { name: "Sara Barbero", table: "Pechino" },
  { name: "Andrea Claudio", table: "Pechino" },
  { name: "Francesca Sblendorio", table: "Pechino" },
  { name: "Stefano Marro", table: "Pechino" },
  { name: "Paola Volpe", table: "Pechino" },
  { name: "Loris Di Renzo", table: "Pechino" },
  { name: "Anna Levi", table: "Palazzo d'estate" },
  { name: "Stefano Gaudino", table: "Palazzo d'estate" },
  { name: "Alessandra Beltramo", table: "Esercito di Terracotta" },
  { name: "Ernesto Ovazza", table: "Esercito di Terracotta" },
  { name: "Fiorella Brino", table: "Isole Kerama" },
  { name: "Lorenzo Brino", table: "Isole Kerama" },
  { name: "Chiara Perlo", table: "Isole Kerama" },
  { name: "Bruno Calisto", table: "Isole Kerama" },
  { name: "Alessandra Sacchi", table: "Esercito di Terracotta" },
  { name: "Emilio Macchi", table: "Esercito di Terracotta" },
  { name: "Anna Stura", table: "Isole Kerama" },
  { name: "Guido Stura", table: "Isole Kerama" },
  { name: "Alberto Stura", table: "Pechino" },
  { name: "Giorgia Canelli", table: "Pechino" },
  { name: "Massimo Dalfelli", table: "Isole Kerama" },
  { name: "Stefania Dalfelli", table: "Isole Kerama" },
  { name: "Mario Garibaldi", table: "Esercito di Terracotta" },
  { name: "Federico Rudino", table: "Zhangjiajie" },
  { name: "Gaia Picozzi", table: "Zhangjiajie" },
  { name: "Tommaso Clemente", table: "Zhangjiajie" },
  { name: "Chiara Battaglini", table: "Zhangjiajie" },
  { name: "Alessandro Salvi", table: "Zhangjiajie" },
  { name: "Raquel Almendros Casado", table: "Zhangjiajie" },
  { name: "Giovanna Marchiaro", table: "Esercito di Terracotta" },
  { name: "Tommaso Rinaudo", table: "Giappone" },
  { name: "Valerio Vaccaro", table: "Palazzo d'estate" },
  { name: "Allegra Blandino", table: "Cina" },
  { name: "Paola Sciacero", table: "Grande Muraglia" },
  { name: "Beatriz Campilongo", table: "Okinawa" },
  { name: "Giulia Kodheli", table: "Città Proibita" }
];
